Neos:
  MetaData:
    defaultEelContext:
      Array: 'TYPO3\Eel\Helper\ArrayHelper'

    metaDataMapping:
      title: '${asset.Title || iptc.Title || exif.imageDescription}'
      caption: '${asset.Caption || iptc.Description}'
      tags: '${Array.concat(asset.tags, iptc.keywords)}'